export interface Philosophy { id: string; version: number; name: string; description: string; rules: string; sourceMode: 'reference' | 'primary' | 'science' | 'independent'; customRules?: string }
export const PHILOSOPHIES: Philosophy[] = [
  { id:'schematic', version:2, name:'Schematic primary evidence', description:'Every article claim is a typed factoid with exact original evidence.', sourceMode:'reference', rules:'Use primary sources or original reporting only. Every factual line in an article must render from a schematic factoid, never free-form uncatalogued prose. Each factoid must use the versioned ontology: stable typed entities, a permitted predicate with its required argument roles and entity types, typed literals and explicit units for numbers, modality and attribution, and evidenced conditions, dates and locations where applicable. Bind the entire claim and every structured field to exact quoted passages from captured original evidence. A separate audit must check both meaning and structure; uncertain or unsupported claims cannot enter articles. Preserve contradictions, qualifications and source assertions rather than declaring reports to be independently established truth. Company claims and experimental results require attribution. Classify each source from its actual content as primary evidence or firsthand original reporting; aggregation, commentary, encyclopedia summaries and press-release rewrites do not qualify. Seek material counterevidence without manufacturing balance. Do not infer identities from similar names, geocode place names or invent missing conditions. Human approval of exact content remains mandatory before publication.' },
  { id:'primary-reporting', version:2, name:'Primary sources and original reporting', description:'Original documents, research and firsthand journalism.', sourceMode:'reference', rules:'Use primary sources or original reporting only. Primary evidence includes original papers (label preprints and do not assume peer review), datasets, code, model cards, official specifications, legal texts and firsthand statements. Original reporting must contain the reporter’s own interviews, document examination, field observation or investigation; aggregation, commentary, encyclopedia summaries and rewrites of press releases do not qualify. Explain the basis for each source classification. Attribute vendor claims, benchmark scores and disputed assertions; distinguish independent replication from self-reported results and record dates, versions, hardware and evaluation conditions where relevant. A company announcement supports what the company says, not independent proof of quality or safety. Separate enacted law from proposals, and identify jurisdiction and effective dates. Seek material counterevidence; never manufacture balance. Exclude unsupported claims and disclose evidence gaps.' },
  { id:'general', version:2, name:'Independent research', description:'Original evidence and reporting from across the web.', sourceMode:'reference', rules:'Research independently of encyclopedias. Compare original evidence across publishers, examine material counterevidence and make uncertainty explicit. Explain the established facts and relevant context in a neutral encyclopedic voice. Distinguish evidence from speculation.' },
  { id:'primary', version:2, name:'Primary sources only', description:'Original research and archived original documents.', sourceMode:'primary', rules:'Use only firsthand evidence, original documents, and original research results. Do not treat reference works, later biographies, reviews, or commentary as primary evidence. Explicitly attribute first-person assertions instead of treating them as independently verified facts. Remove claims when the source does not qualify as primary evidence.' },
  { id:'scientific', version:2, name:'Scientific literature', description:'Journal literature, with study limitations made explicit.', sourceMode:'science', rules:'Use scientific journal publications. Distinguish original studies from reviews, association from causation, and findings from hypotheses. State relevant uncertainty and limitations supported by the abstract. Do not assert peer review or scientific consensus solely from indexing metadata. Exclude preprints, press releases, and non-scientific commentary.' },
  { id:'independent', version:2, name:'Independent sources', description:'Non-corporate sources; exclude news ownership and sponsorship conflicts.', sourceMode:'independent', rules:'Exclude corporate-owned news outlets, corporate publications, sponsored material, press releases, and promotional claims. Require evidence of non-corporate authorship or ownership; do not assume that a .org address establishes independence. Do not imply that nonprofit ownership alone guarantees accuracy. Attribute contested claims and avoid promotional wording.' },
  { id:'perspectives', version:2, name:'Competing perspectives', description:'Credible disagreements, weighted by the evidence.', sourceMode:'reference', rules:'Identify credible disagreements represented in the evidence. Present the strongest supported positions and explain where the evidence differs. Weight perspectives by evidence, not equal airtime. Never invent an opposing view or manufacture controversy. Say when the available sources cannot establish competing positions.' },
];
export function requiresFactoids(p:{id:string;version:number}|undefined){return p?.id==='schematic'&&p.version===2;}
const LEGACY_PHILOSOPHIES: Philosophy[] = [
  { id:'general', version:1, name:'General reference', description:'Broad context from reliable reference sources.', sourceMode:'reference', rules:'Explain the established facts and relevant context in a neutral encyclopedic voice. Distinguish evidence from speculation.' },
  { id:'primary', version:1, name:'Primary sources only', description:'Original research and archived original documents.', sourceMode:'primary', rules:'Use only firsthand evidence, original documents, and original research results. Do not treat reference works, later biographies, reviews, or commentary as primary evidence. Explicitly attribute first-person assertions instead of treating them as independently verified facts. Remove claims when the source does not qualify as primary evidence.' },
  { id:'scientific', version:1, name:'Scientific literature', description:'Journal literature, with study limitations made explicit.', sourceMode:'science', rules:'Use scientific journal publications. Distinguish original studies from reviews, association from causation, and findings from hypotheses. State relevant uncertainty and limitations supported by the abstract. Do not assert peer review or scientific consensus solely from indexing metadata. Exclude preprints, press releases, and non-scientific commentary.' },
  { id:'independent', version:1, name:'Independent sources', description:'Nonprofit reference collections; no corporate news or press releases.', sourceMode:'independent', rules:'Exclude corporate-owned news outlets, corporate publications, sponsored material, press releases, and promotional claims. Use the nonprofit reference collections supplied. Do not imply that nonprofit ownership alone guarantees accuracy. Attribute contested claims and avoid promotional wording.' },
  { id:'perspectives', version:1, name:'Competing perspectives', description:'Credible disagreements, weighted by the evidence.', sourceMode:'reference', rules:'Identify credible disagreements represented in the evidence. Present the strongest supported positions and explain where the evidence differs. Weight perspectives by evidence, not equal airtime. Never invent an opposing view or manufacture controversy. Say when the available sources cannot establish competing positions.' },
];
export function resolvePhilosophy(id: unknown = 'general', customRules?: unknown, version:unknown=2): Philosophy {
  if(version!==1&&version!==2)throw Error('Unsupported research philosophy version.');
  if (id === 'custom') {
    if (typeof customRules !== 'string' || customRules.trim().length < 20 || customRules.trim().length > 2000) throw new Error('Custom research rules must contain 20–2,000 characters.');
    return { id:'custom',version,name:'Custom standards',description:'Contributor-defined standards for independent web research.',sourceMode:'reference',rules:customRules.trim(),customRules:customRules.trim() };
  }
  const preset = (version===1?LEGACY_PHILOSOPHIES:PHILOSOPHIES).find(p=>p.id===id);
  if (!preset) throw new Error('Choose a supported research philosophy.');
  return {...preset};
}
