import ArticleImages from './ArticleImages';
import React,{useEffect,useState,useRef} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {PHILOSOPHIES} from '../shared/philosophies';
import type {Article} from '../server/research';
import {communityApi,communityOnly} from './community-api';
import './community.css';

type Contributor={id:string;username:string;role:string;reputation:number;createdAt:number};
type Entry={id:string;title:string;username:string;policyName:string;policyKey:string;topicKey:string;status?:string;moderation?:{summary?:string;serviceUnavailable?:boolean};createdAt:number};
export function ContributorLogin({onDone}:{onDone:()=>void}){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[requestId,setRequestId]=useState(''),[development,setDevelopment]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{
   if(!requestId){const result=await communityApi('/auth/start','POST',{email});setRequestId(result.requestId);setDevelopment(result.development);}
   else{await communityApi('/auth/verify','POST',{requestId,code});onDone();}
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="contributor-login" onSubmit={submit}><p>Verify your email to contribute. Readers do not need an account.</p>{error&&<p className="error" role="alert">{error}</p>}{!requestId?<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label>:<><p>Enter the eight-digit code for {email}. It expires in 10 minutes.</p><label>Verification code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} inputMode="numeric" pattern="[0-9]{8}" maxLength={8} autoComplete="one-time-code" required/></label>{development&&<button type="button" className="development-mailbox" onClick={async()=>{try{setCode((await communityApi('/dev/mailbox/'+requestId)).code);}catch(e){setError((e as Error).message);}}}>Open local development mailbox</button>}</>}<button className="primary" disabled={busy}>{busy?'Please wait…':requestId?'Verify and sign in':'Send sign-in code'}</button>{requestId&&<button type="button" onClick={()=>{setRequestId('');setCode('');}}>Use another email</button>}</form>;
}
export function PublishDialog({article,onClose}:{article:Article;onClose:()=>void}){
 const [user,setUser]=useState<Contributor|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[remaining,setRemaining]=useState(100),[dev,setDev]=useState(false);
 async function refresh(){try{const [me,config]=await Promise.all([communityApi('/me'),communityApi('/config')]);setUser(me.user);setRemaining(me.uploadsRemaining??100);setDev(config.development);}catch(e){setError((e as Error).message);}finally{setLoaded(true);}}
 useEffect(()=>{void refresh();},[]);
 async function publish(){setBusy(true);setError('');try{
   const {title,topic,markdown,model,philosophy}=article;
   setResult(await communityApi('/submissions','POST',{confirmPublic:confirmed,article:{title,topic,markdown,model,philosophy,sources:article.sources.map(({id,title,url})=>({id,title,url}))}}));
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="modal-backdrop" onClick={onClose}><section className="modal publish-dialog" role="dialog" aria-modal="true" aria-labelledby="publish-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close publishing dialog">×</button><h2 id="publish-title">Contribute this article</h2>{dev&&<p className="preview-banner">Local preview only. Nothing is uploaded to the internet.</p>}{error&&<p className="error" role="alert">{error}</p>}{!loaded?<p>Connecting to the library…</p>:result?<><h3>{result.duplicate?'Already submitted':result.status==='published'?'Published':'Submitted for review'}</h3><p>{result.status==='published'?'The article is available in the shared library.':'The article must pass source and moderation checks before readers can see it.'}</p><a href="/community/mine">View your submissions →</a></>:user?<><p><b>{article.title}</b><br/>{article.philosophy?.name||'General reference'} · credited to <b>@{user.username}</b></p><p>{remaining} of 100 uploads remaining today. Resets at midnight UTC.</p><label className="consent"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I want to share the final article, its source links, and my contributor name publicly. I have permission to share this text.</label><p className="small">Your email, ChatGPT credentials, and private draft history are not uploaded. The server retrieves its own source excerpts and checks the article.</p><button className="primary" disabled={busy||!confirmed||remaining<=0} onClick={()=>void publish()}>{busy?'Submitting…':'Submit for review'}</button></>:<ContributorLogin onDone={()=>void refresh()}/>}</section></div>;
}
const localResearch=(topic:string,philosophy='general')=>`http://127.0.0.1:4317/?topic=${encodeURIComponent(topic)}&philosophy=${encodeURIComponent(philosophy)}`;
function ArticleText({text}:{text:string}){return <Markdown remarkPlugins={[remarkGfm]} components={{h2:({children})=><h2 id={String(children).toLowerCase().replace(/[^a-z0-9]+/g,'-')}>{children}</h2>,a:({href,children})=>href?.startsWith('#source-')?<sup className="reference"><a href={href}>[{children}]</a></sup>:<a href={href} target="_blank" rel="noreferrer">{children}</a>,img:()=>null}}>{text}</Markdown>;}
export default function Community(){
 const loadEpoch=useRef(0);
 const [path,setPath]=useState(location.pathname),[user,setUser]=useState<Contributor|null>(null),[config,setConfig]=useState<any>(null),[me,setMe]=useState<any>(null),[login,setLogin]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [entries,setEntries]=useState<Entry[]>([]),[data,setData]=useState<any>(null),[versions,setVersions]=useState<Entry[]>([]),[q,setQ]=useState(''),[policy,setPolicy]=useState(''),[username,setUsername]=useState('');
 const [report,setReport]=useState(''),[reportOpen,setReportOpen]=useState(false),[decisionReason,setDecisionReason]=useState(''),[verified,setVerified]=useState(false),[abuse,setAbuse]=useState(false);
 const isArticle=path.startsWith('/community/article/'),isProfile=path.startsWith('/community/profile/'),isMine=path==='/community/mine',isModeration=path==='/community/moderation',isReview=path.startsWith('/community/review/');
 function navigate(next:string){if(next===path){void load();return;}loadEpoch.current++;history.pushState({},'',next);setPath(next);setError('');setNotice('');setData(null);setEntries([]);setVersions([]);setReportOpen(false);setDecisionReason('');setVerified(false);setAbuse(false);window.scrollTo(0,0);}
 async function account(){const value=await communityApi('/me');setMe(value);setUser(value.user);}
 useEffect(()=>{const handler=()=>{loadEpoch.current++;setData(null);setPath(location.pathname);};window.addEventListener('popstate',handler);void Promise.all([account(),communityApi('/config').then(setConfig)]).catch(e=>setError(e.message));return()=>window.removeEventListener('popstate',handler);},[]);
 async function load(){const epoch=++loadEpoch.current;const setCurrentData=(v:any)=>{if(epoch===loadEpoch.current)setData(v);};const setCurrentEntries=(v:Entry[])=>{if(epoch===loadEpoch.current)setEntries(v);};const setCurrentVersions=(v:Entry[])=>{if(epoch===loadEpoch.current)setVersions(v);};setBusy(true);setError('');try{
   if(isArticle){const a=await communityApi('/articles/'+path.split('/').at(-1));setCurrentData(a);setCurrentVersions((await communityApi('/versions?topic='+encodeURIComponent(a.article.title))).versions);}
   else if(isProfile)setCurrentData(await communityApi('/profiles/'+path.split('/').at(-1))); 
   else if(isMine){setCurrentEntries((await communityApi('/submissions')).submissions);await account();}
   else if(isModeration)setCurrentData(await communityApi('/admin/queue'));
   else if(isReview)setCurrentData(await communityApi('/admin/submissions/'+path.split('/').at(-1)));
   else setCurrentEntries((await communityApi('/articles?q='+encodeURIComponent(q)+'&philosophy='+encodeURIComponent(policy))).articles);
 }catch(e){if(epoch===loadEpoch.current)setError((e as Error).message);}finally{if(epoch===loadEpoch.current)setBusy(false);}}
 useEffect(()=>{void load();},[path]);
 useEffect(()=>{if(!isMine||!entries.some(e=>e.status==='pending'))return;const timer=setInterval(()=>void load(),4000);return()=>clearInterval(timer);},[isMine,entries]);
 async function action(fn:()=>Promise<unknown>){setError('');setNotice('');setBusy(true);try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const title=isArticle?data?.article.title||'Article':isProfile?data?.profile.username?'Contributor: '+data.profile.username:'Contributor':isMine?'Your contributions':isModeration?'Moderation queue':isReview?'Review submission':'Community library';
 const navigateLink=(event:React.MouseEvent,path:string)=>{event.preventDefault();navigate(path);};
 function list(items:Entry[]){return <div className="community-list">{items.length?items.map(e=><section key={e.id}><h3><a href={'/community/article/'+e.id} onClick={event=>{if(!e.status||e.status==='published')navigateLink(event,'/community/article/'+e.id);else event.preventDefault();}}>{e.title}</a></h3><p><span className="policy-label">{e.policyName}</span> · by <a href={'/community/profile/'+e.username} onClick={event=>navigateLink(event,'/community/profile/'+e.username)}>@{e.username}</a>{e.status&&<> · <b className={'submission-status '+e.status}>{e.status}</b></>}</p>{e.moderation?.summary&&<p className="small">{e.moderation.summary}</p>}</section>):<p className="empty-community">No published articles in this collection yet. Generate one locally and contribute it.</p>}</div>;}
 return <div className="app community-app"><header className="header"><a className="brand" href="/community" onClick={e=>navigateLink(e,'/community')}><span><strong>WikiChat</strong><small>The shared encyclopedia</small></span></a><form className="search" onSubmit={e=>{e.preventDefault();if(path!=='/community')navigate('/community');else void load();}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the shared library" aria-label="Search shared articles"/><button>Search</button></form><div className="user-links">{user?<button onClick={()=>navigate('/community/mine')}>@{user.username}</button>:<button onClick={()=>setLogin(true)}>Log in to contribute</button>}</div></header>
 <div className="layout"><aside className="sidebar"><nav className="main-navigation"><a href="/community" onClick={e=>navigateLink(e,'/community')}>Community library</a><a href={localResearch('')}>Research locally</a>{!communityOnly&&<a href="/">Your local articles</a>}{user&&<><a href="/community/mine" onClick={e=>navigateLink(e,'/community/mine')}>Your contributions</a><a href={'/community/profile/'+user.username} onClick={e=>navigateLink(e,'/community/profile/'+user.username)}>Your profile</a></>}{user?.role==='admin'&&<a href="/community/moderation" onClick={e=>navigateLink(e,'/community/moderation')}>Moderation queue</a>}</nav><div className="side-title">Research philosophies</div>{PHILOSOPHIES.map(p=><p key={p.id} className="small">{p.name}</p>)}</aside>
 <main><div className="title-row"><h1>{title}</h1><span className="language">English</span></div><div className="page-tabs"><div><button className="selected">{isArticle?'Article':'Community'}</button></div><div><a href="/community" onClick={e=>navigateLink(e,'/community')}>Browse</a>{user?.role==='admin'&&<a href="/community/moderation" onClick={e=>navigateLink(e,'/community/moderation')}>Moderate</a>}</div></div><div className="site-subtitle">From WikiChat, the shared encyclopedia</div>
 {config?.development&&<div className="preview-banner">Local community preview. Email verification uses a development mailbox. Nothing here is published to the internet.</div>}{error&&<div className="error" role="alert">{error}</div>}{notice&&<p className="success-notice" role="status">{notice}</p>}{busy&&<p role="status">Loading…</p>}
 {!isArticle&&!isProfile&&!isMine&&!isModeration&&!isReview&&<><p>One topic, different research standards. Read for free, switch philosophies, or contribute a missing version.</p><form className="community-filter" onSubmit={e=>{e.preventDefault();void load();}}><label>Research philosophy<select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="">All philosophies</option>{PHILOSOPHIES.map(p=><option key={p.id} value={`${p.id}@${p.version}`}>{p.name}</option>)}</select></label><button className="primary">Filter articles</button></form>{list(entries)}</>}
 {isArticle&&data&&<><div className="version-switcher"><strong>Research philosophy</strong><div>{PHILOSOPHIES.map(p=>{const match=versions.find(v=>v.policyKey===`${p.id}@${p.version}`);return match?<button key={p.id} className={data.article.philosophy?.id===p.id?'active':''} onClick={()=>navigate('/community/article/'+match.id)}>{p.name}</button>:<a className="missing-version" key={p.id} href={localResearch(data.article.title,p.id)} title="Generate this missing version locally">{p.name} <small>Research this version ↗</small></a>;})}</div></div><p className="contributor-credit">Contributed by <a href={'/community/profile/'+data.contributor.username} onClick={e=>navigateLink(e,'/community/profile/'+data.contributor.username)}>@{data.contributor.username}</a> · Reputation {data.contributor.reputation} · AI-assisted</p><details className="philosophy-details"><summary>{data.article.philosophy.name} · version {data.article.philosophy.version} — view the research rules</summary><p>{data.article.philosophy.rules}</p></details><article className="wiki-body"><ArticleImages images={data.article.images}/><ArticleText text={data.article.markdown}/></article><h2>References</h2><ol className="references">{data.article.sources.map((s:any)=><li id={'source-'+s.id} key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.provider||'Source'}</li>)}</ol><div className="reader-actions"><button onClick={()=>{if(!user)setLogin(true);else void action(async()=>{await communityApi('/articles/'+data.article.id+'/helpful','POST');setNotice('Thanks. Your endorsement was recorded.');});}}>Helpful article</button><button onClick={()=>{if(!user)setLogin(true);else setReportOpen(!reportOpen);}}>Report a problem or suggest a correction</button></div>{reportOpen&&<form onSubmit={e=>{e.preventDefault();void action(async()=>{await communityApi('/articles/'+data.article.id+'/report','POST',{reason:report});setReportOpen(false);setNotice('Your report was sent to the moderation queue.');});}}><label>Explain the problem and include supporting evidence<textarea value={report} onChange={e=>setReport(e.target.value)} minLength={20} maxLength={2000} required/></label><button className="primary" disabled={busy}>Send report</button></form>}{versions.length>1&&<details><summary>All published contributions for this topic ({versions.length})</summary>{list(versions)}</details>}</>}
 {isProfile&&data&&<><div className="profile-summary"><h2>@{data.profile.username}</h2><p><b>{data.profile.reputation}</b> reputation · {data.profile.level}</p><p className="small">Joined {new Date(data.profile.joinedAt*1000).toLocaleDateString()}. Reputation comes from reader endorsements and helpful reports, not upload volume.</p></div><h2>Published contributions</h2>{list(data.articles)}</>}
 {isMine&&<>{user?<><p><b>{me?.uploadsRemaining??100}</b> of 100 uploads remaining today. Resets at midnight UTC.</p><p>Reputation: <b>{user.reputation}</b>. Publishing more articles does not automatically increase it.</p>{user.username.startsWith('contributor-')&&<form className="username-form" onSubmit={e=>{e.preventDefault();void action(async()=>{await communityApi('/me','PATCH',{username});await account();setNotice('Your public username is set.');});}}><label>Choose your public username<input value={username} onChange={e=>setUsername(e.target.value)} pattern="[a-z][a-z0-9_-]{2,23}" required placeholder="your-name"/></label><button className="primary">Set username</button><p className="small">This name stays attached to your contributions.</p></form>}<button onClick={()=>void action(async()=>{await communityApi('/auth/logout','POST');await account();navigate('/community');})}>Sign out of the shared library</button><h2>Your submissions</h2>{list(entries)}</>:<ContributorLogin onDone={()=>{void account();void load();}}/>}</>}
 {isModeration&&data&&<><h2>Submissions awaiting review</h2>{data.submissions.length?data.submissions.map((s:any)=><section className="queue-item" key={s.id}><h3><button onClick={()=>navigate('/community/review/'+s.id)}>{s.title}</button></h3><p>{s.policyName} · @{s.username} · {s.status}</p><p className="small">{s.moderation.summary||'Automatic review pending.'}</p></section>):<p>No submissions need review.</p>}<h2>Reader reports</h2>{data.reports.length?data.reports.map((r:any)=><section className="queue-item" key={r.id}><h3>{r.title}</h3><p>{r.reason}</p><p className="small">Reported by @{r.username}</p><button onClick={()=>navigate('/community/review/'+r.article_id)}>Inspect article / withdraw</button><ReportResolution id={r.id} onDone={()=>void load()}/></section>):<p>No open reports.</p>}</>}
 {isReview&&data&&<><p>Submitted by @{data.username} · <b>{data.status}</b></p><h2>{data.article.title}</h2>{data.sourceError&&<p className="error">{data.sourceError}</p>}<p>{data.moderation.summary}</p><details><summary>Automatic moderation details</summary><pre>{JSON.stringify(data.moderation,null,2)}</pre></details><details open><summary>Article and source evidence</summary><div className="wiki-body"><ArticleImages images={data.article.images}/><ArticleText text={data.article.markdown}/></div><h2>Source evidence</h2>{data.article.sources.map((s:any)=><details key={s.id}><summary>{s.id}. {s.title}</summary><a href={s.url} target="_blank" rel="noreferrer">Open original source ↗</a><p>{s.extract||'Evidence not retrieved.'}</p></details>)}</details><form className="moderator-decision" onSubmit={e=>e.preventDefault()}><label>Decision reason<textarea value={decisionReason} onChange={e=>setDecisionReason(e.target.value)} minLength={20} maxLength={2000}/></label><label className="consent"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I reviewed every claim, its cited evidence, and the research philosophy.</label><label className="consent"><input type="checkbox" checked={abuse} onChange={e=>setAbuse(e.target.checked)}/>Confirmed spam or abuse (applies a reputation penalty when rejected or withdrawn).</label><div className="decision-buttons">{['approve','reject','withdraw','retry'].map(a=><button key={a} className={a==='approve'?'primary':''} disabled={busy||decisionReason.trim().length<20||(a==='approve'&&(!verified||!!data.sourceError))} onClick={()=>void action(async()=>{await communityApi('/admin/submissions/'+data.article.id+'/decision','POST',{action:a,reason:decisionReason,verifiedSources:verified,confirmedAbuse:abuse});navigate('/community/moderation');})}>{a[0].toUpperCase()+a.slice(1)}</button>)}</div></form></>}
 <footer><p>Reading is free. Published articles are AI-assisted and reviewed; that is not a guarantee of accuracy.</p><p>WikiChat is an independent project, not affiliated with Wikipedia or the Wikimedia Foundation.</p></footer></main><aside className="appearance"><div className="side-title">Contributing</div><p>100 submissions per contributor per day. Duplicate submissions do not create new articles.</p><p>Each submission goes through source checks and moderation before publication.</p>{config&&!config.moderationReady&&<p className="small">Automatic moderation is not configured. Submissions will be held for manual review.</p>}<div className="side-title">Reputation</div><p className="small">Helpful endorsements: +2<br/>Upheld reports: +1<br/>Confirmed abuse: −10<br/>No points for upload volume.</p><a href={localResearch(isArticle?data?.article.title||'':'')}>Open the local researcher ↗</a></aside></div>
 {login&&<div className="modal-backdrop" onClick={()=>setLogin(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Contributor sign-in" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close sign-in" onClick={()=>setLogin(false)}>×</button><h2>Contributor sign-in</h2><ContributorLogin onDone={()=>{setLogin(false);void account();void load();}}/></section></div>}
 </div>;
}
function ReportResolution({id,onDone}:{id:string;onDone:()=>void}){const [reason,setReason]=useState(''),[error,setError]=useState('');async function decide(upheld:boolean){try{await communityApi('/admin/reports/'+id,'POST',{reason,upheld});onDone();}catch(e){setError((e as Error).message);}}return <details><summary>Resolve this report</summary>{error&&<p role="alert">{error}</p>}<textarea aria-label="Report resolution" value={reason} onChange={e=>setReason(e.target.value)} minLength={20} maxLength={2000}/><button disabled={reason.trim().length<20} onClick={()=>void decide(true)}>Uphold report</button><button disabled={reason.trim().length<20} onClick={()=>void decide(false)}>Dismiss report</button><p className="small">Resolving a report does not remove the article. Inspect the article and choose Withdraw if it should be taken down.</p></details>;}
