import React,{useState} from 'react';
import type {Article} from '../server/research';
import site from '../github/site.json';
import {requiresFactoids} from '../shared/philosophies';
export default function GitHubContribution({article,onClose,api}:{article:Article;onClose:()=>void;api:(path:string)=>Promise<any>}){
 const schematic=requiresFactoids(article.philosophy),folder=schematic?'knowledge/changes':'articles';
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function download(){setBusy(true);setError('');try{
  const data=schematic?await api(article.id.startsWith('knowledge-')?'knowledge/articles/'+encodeURIComponent(article.knowledge!.entityId)+'/bundle?subject='+encodeURIComponent(article.subjectId!):'articles/'+encodeURIComponent(article.id)+'/knowledge-bundle'):{subjectId:article.subjectId,title:article.title,topic:article.topic,markdown:article.markdown,philosophy:article.philosophy,model:article.model,images:article.images,sources:article.sources.map(({id,title,url})=>({id,title,url}))};
  const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(article.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,65)||'article')+'-'+(article.philosophy?.id||'general')+'.json';a.click();URL.revokeObjectURL(a.href);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label="Contribute research on GitHub" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close contribution dialog" onClick={onClose}>×</button><h2>Contribute this research</h2><p>Your search can become part of the shared encyclopedia.</p>{schematic&&<p>Contribute the underlying factoids and exact evidence. Articles are generated from the reviewed bundle; prose cannot bypass these standards.</p>}<ol><li>Download the {schematic?'factoid bundle':'article file'}.</li><li>Add it to the repository’s <code>{folder}/</code> folder in a pull request.</li><li>Comment <code>/submit</code> on your PR to enter the review queue.</li></ol><p>Each account can submit 100 revisions per UTC day. Review and publication require explicit approval.</p>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy} onClick={()=>void download()}>{busy?'Preparing…':schematic?'Download factoid bundle for GitHub':'Download article for GitHub'}</button>{site.repository?<p><a href={'https://github.com/'+site.repository+'/upload/main/'+folder} target="_blank" rel="noreferrer">Open contribution repository ↗</a></p>:<p>The repository destination has not been configured yet. You can save the research now.</p>}<p className="small">{schematic?'The export contains schematic claims, entity identities, audit results, capture hashes and exact quotes. Selected illustrations and credit are included. Full source captures and local approvals stay private.':'The final article, its illustration and credit, standards, and source links are exported.'} Your email, ChatGPT credentials, and private draft history stay local. A public PR’s text is visible before approval.</p></section></div>;
}
