import React,{useEffect,useState} from 'react';
import {EvidencePreviewProvider,Factoid} from './EvidencePreview';
import {emptyKnowledge,knowledgeViews,type KnowledgeSnapshot,type FactRevision} from '../shared/knowledge';
import type {Article} from '../server/research';
export default function KnowledgeExplorer({subjectId,model,budget,api,onArticle}:{subjectId:string;model:string;budget:{requests:number;minutes:number};api:(path:string,method?:string,body?:unknown)=>Promise<any>;onArticle:(article:Article)=>void}){
 const [snapshot,setSnapshot]=useState<KnowledgeSnapshot>(emptyKnowledge()),[policyKey,setPolicyKey]=useState(''),[mode,setMode]=useState<'preview'|'approved'>('preview');
 const [tab,setTab]=useState<'facts'|'timeline'|'concepts'|'map'>('facts'),[selected,setSelected]=useState<FactRevision|null>(null),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[usage,setUsage]=useState(''),[jobs,setJobs]=useState<any[]>([]),[candidates,setCandidates]=useState(0);
 const [intakeSource,setIntakeSource]=useState<{title:string;url:string}|null>(null),[intakeFacts,setIntakeFacts]=useState<{id:string;statement:string;outcome?:string}[]>([]);
 const [articleEntities,setArticleEntities]=useState<string[]>([]);
 const controller=React.useRef<AbortController|null>(null);
 const scope='subject='+encodeURIComponent(subjectId);
 const views=knowledgeViews(snapshot,policyKey,mode);
 const labels=new Map(snapshot.entities.map(e=>[e.id,e.label]));
 async function load(){const result=await api('knowledge?'+scope+'&mode='+mode);setSnapshot(result.snapshot);setPolicyKey(result.policyKey);setArticleEntities(result.articleEntities||[]);setJobs(await api('knowledge/jobs'));}
 useEffect(()=>{let version=-1;const update=async()=>{try{const event=await api('knowledge/events');if(event.version!==version){version=event.version;await load();}}catch(e){setError((e as Error).message);}};void update();const timer=window.setInterval(()=>void update(),4000);return()=>{window.clearInterval(timer);controller.current?.abort();};},[subjectId,mode]);
 async function ingest(event?:React.FormEvent,resume?:any){
  event?.preventDefault();if(busy)return;setBusy(true);setError('');setSelected(null);setStatus('Preparing source intake…');setUsage('');setCandidates(0);setIntakeSource(null);setIntakeFacts([]);
  const abort=new AbortController();controller.current=abort;
  try{
   // The session endpoint exposes the same local CSRF token used by the parent app.
   const session=await api('session');const r=await fetch('/api/knowledge/ingest',{method:'POST',headers:{'Content-Type':'application/json','X-WikiChat-Token':session.csrf},body:JSON.stringify({subjectId,url,model:resume?.model||model,resumeId:resume?.id,budget}),signal:abort.signal});
   if(!r.ok)throw Error((await r.json()).error);if(!r.body)throw Error('No source stream received.');
   let pending='';const decoder=new TextDecoder();let complete=false;
   for await(const chunk of r.body as any){pending+=decoder.decode(chunk,{stream:true});let at;
    while((at=pending.indexOf('\n'))>=0){const line=pending.slice(0,at);pending=pending.slice(at+1);if(!line)continue;const e=JSON.parse(line);
     if(e.type==='progress')setStatus(e.message);
     if(e.type==='usage')setUsage(`${e.used}/${e.limit} requests`);
     if(e.type==='source')setIntakeSource(e.source);
     if(e.type==='fact-candidate'){setCandidates(n=>n+1);setIntakeFacts(facts=>[...facts,{id:e.fact.id,statement:e.fact.statement}]);}
     if(e.type==='fact-audited')setIntakeFacts(facts=>[...facts.filter(f=>f.id!==e.fact.id),{id:e.fact.id,statement:e.fact.statement,outcome:e.assessment.outcome}]);
     if(e.type==='error')throw Error(e.message);
     if(e.type==='complete'){complete=true;setStatus(`${e.facts} supported claims added to the draft views. Human approval pending.`);await load();}
    }
   }
   if(!complete)throw Error('The source task was interrupted. Continue it with a fresh allowance.');
  }catch(e){setError(abort.signal.aborted?'Source task stopped; retained work can be resumed.':(e as Error).message);}finally{setBusy(false);controller.current=null;void load().catch(e=>setError((e as Error).message));}
 }
 async function openEntity(id:string){if(!articleEntities.includes(id)){setError('More supported claims are needed to form this article. Read another original source to expand it.');return;}try{setError('');onArticle(await api('knowledge/articles/'+encodeURIComponent(id)+'?'+scope+'&mode='+mode));}catch(e){setError(e instanceof Error?e.message:'Cannot build this article.');}}
 return <EvidencePreviewProvider scopeKey={subjectId+':'+mode+':'+tab} load={ref=>api('knowledge/revisions/'+encodeURIComponent(ref.revisionId)+'/evidence?'+scope+'&mode='+mode+'&digest='+encodeURIComponent(ref.digest))}><section aria-label="Shared knowledge">
  <p>Articles, timelines and relationships draw from the same evidence-backed claim revisions. New sources propose changes across these views.</p>
  <label>Claim view <select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} disabled={busy}><option value="preview">AI-audited drafts</option><option value="approved">Locally approved claims</option></select></label>
  <p className="small">{views.facts.length} current claims · {views.nodes.length} entities · {snapshot.revisions.length-views.facts.length} other revisions or audit outcomes. Draft claims have not received human approval.</p>
  <form className="research-box" onSubmit={e=>void ingest(e)}><h2>Read a new source</h2><p>Extract atomic claims, check their exact passages in a second pass, and update the shared draft views.</p><label>Original source URL <input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…" disabled={busy} maxLength={1800}/></label><button className="primary" disabled={busy||!model||!url}>Process source</button><p className="small">Allowance: {budget.requests} model requests, {budget.minutes} minutes. Reading these views uses no model calls.</p></form>
  {busy&&<button onClick={()=>controller.current?.abort()}>Stop source intake</button>}
  {status&&<p role="status">{status} {usage} {candidates>0&&`· ${candidates} extracted candidates`}</p>}
  {intakeSource&&<p>Source: <a href={intakeSource.url} target="_blank" rel="noreferrer">{intakeSource.title}</a></p>}
  {intakeFacts.length>0&&<details open={busy}><summary>Source intake · {intakeFacts.length} claim candidates</summary>{intakeFacts.map(f=><div key={f.id} className={'document-block'+(f.outcome==='supported'?' just-edited':'')}><p>{f.statement}</p><p className="small">{f.outcome?`Audit: ${f.outcome}`:'Awaiting evidence audit'} · human approval pending</p></div>)}</details>}
  {error&&<p className="error" role="alert">{error}</p>}
  {jobs.filter(j=>j.subjectId===subjectId).map(j=><p key={j.id}><button disabled={busy} onClick={()=>void ingest(undefined,j)}>Continue source task</button> · {j.url} · {j.requestsUsed} requests used</p>)}
  <div className="page-tabs" role="tablist" aria-label="Knowledge views"><div>{(['facts','timeline','concepts','map'] as const).map(t=><button role="tab" key={t} aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{({facts:'Claims',timeline:'Timeline',concepts:'Concept map',map:'Map'} as const)[t]}</button>)}</div></div>
  {tab==='facts'&&<><p className="small">Hover a claim to see its exact source passage. Click to keep the evidence open.</p>{views.facts.length?<ul>{views.facts.map(f=><li key={f.id}><Factoid inline reference={{revisionId:f.id,digest:f.digest,statement:f.statement}}><button className="inline-link" onClick={()=>setSelected(f)}>{f.statement}</button></Factoid></li>)}</ul>:<p>No claims in this view yet. Process an original source to begin.</p>}</>}
  {tab==='timeline'&&<><p>Dates refer to the asserted event or condition. Undated claims remain outside the timeline.</p><ol>{views.timeline.map(f=><li key={f.id}><strong>{f.time?.start||'Open start'}{f.time?.end&&f.time.end!==f.time.start?' — '+f.time.end:''}</strong> · {f.time?.precision}<br/><Factoid inline reference={{revisionId:f.id,digest:f.digest,statement:f.statement}}><button className="inline-link" onClick={()=>setSelected(f)}>{f.statement}</button></Factoid></li>)}</ol><p>{views.undated.length} undated claims.</p></>}
  {tab==='concepts'&&<><p>Connections are explicit claim arguments, not similarity inferred from names.</p><ConceptGraph nodes={views.nodes.slice(0,24)} edges={views.edges} onFact={id=>setSelected(views.facts.find(f=>f.factId===id)||null)}/>{views.nodes.length>24&&<p>The diagram shows its first 24 entities; the complete relation list follows.</p>}<ul>{views.edges.map((e,i)=><li key={i}><button className="inline-link" onClick={()=>setSelected(views.facts.find(f=>f.id===e.revisionId)||null)}>{labels.get(e.from)} → {e.predicate.replaceAll('_',' ')} → {labels.get(e.to)} ({e.role})</button></li>)}</ul></>}
  {tab==='map'&&<><p>Points require explicit, evidenced coordinates and a location role. Mentioning a place does not put a claim on the map.</p>{views.geojson.features.length?<svg viewBox="0 0 720 360" width="100%" role="img" aria-label="Evidenced coordinates in longitude and latitude">{[-180,-90,0,90,180].map(lon=><g key={lon}><line x1={(lon+180)*2} x2={(lon+180)*2} y1="0" y2="360" stroke="var(--border)"/><text x={(lon+180)*2+3} y="350" fontSize="12">{lon}°</text></g>)}{[-90,0,90].map(lat=><line key={lat} x1="0" x2="720" y1={(90-lat)*2} y2={(90-lat)*2} stroke="var(--border)"/>)}{views.geojson.features.map(f=><g key={f.id}><circle cx={(f.geometry.coordinates[0]+180)*2} cy={(90-f.geometry.coordinates[1])*2} r="5" fill="var(--blue)"/><title>{f.properties.statement}</title></g>)}</svg>:<p>No evidenced coordinates are available yet.</p>}<details><summary>GeoJSON export</summary><pre>{JSON.stringify(views.geojson,null,2)}</pre></details></>}
  {selected&&<aside className="scope-note"><h2>Claim and evidence</h2><p>{selected.statement}</p><p>{selected.modality}{selected.attribution?' · '+selected.attribution:''} · {selected.predicate.replaceAll('_',' ')}</p>{selected.evidence.map((e,i)=>{const c=snapshot.captures.find(c=>c.id===e.captureId);return <section key={i}><a href={c?.url} target="_blank" rel="noreferrer">{c?.title}</a><blockquote>{e.quote}</blockquote><p>{e.stance} · captured-text characters {e.start}–{e.end}</p><p>{c?.classificationReason}</p></section>;})}{selected.time&&<p>Date basis: {selected.time.basis}</p>}{selected.uncertainties.map((u,i)=><p key={i}>Uncertainty: {u}</p>)}{selected.conflictsWith.length>0&&<p>Conflicts recorded: {selected.conflictsWith.join(', ')}</p>}<p>Audit: {snapshot.audits.find(a=>a.revisionId===selected.id)?.reason}</p><details><summary>Exact revision and approval</summary><p>{selected.id}</p><p>Digest: {selected.digest}</p><p>{snapshot.approvals.some(a=>a.revisionId===selected.id)?'Locally approved':'Human approval pending'}</p></details></aside>}
  {views.nodes.length>0&&<section><h2>Articles from shared claims</h2><p>Each entity view reuses the same revisions and citations. {mode==='preview'?'These draft article projections await human approval.':'These projections use locally approved claims; publication remains separate.'} Red links need more evidence.</p><ul>{views.nodes.map(e=><li key={e.id}><button className={'inline-link'+(articleEntities.includes(e.id)?'':' missing-article')} title={articleEntities.includes(e.id)?'Read article projection':'More evidence needed'} onClick={()=>void openEntity(e.id)}>{e.label}</button>{!articleEntities.includes(e.id)&&<small> · More evidence needed</small>}</li>)}</ul></section>}
 </section></EvidencePreviewProvider>;
}
function ConceptGraph({nodes,edges,onFact}:{nodes:{id:string;label:string}[];edges:{from:string;to:string;predicate:string;factId:string}[];onFact:(id:string)=>void}){
 if(!nodes.length)return <p>No evidenced relationships yet.</p>;
 const points=new Map(nodes.map((n,i)=>[n.id,{x:360+260*Math.cos(2*Math.PI*i/nodes.length),y:220+160*Math.sin(2*Math.PI*i/nodes.length)}]));
 return <svg viewBox="0 0 720 440" width="100%" role="img" aria-label="Concept relationships grounded in shared claims">{edges.filter(e=>points.has(e.from)&&points.has(e.to)).map((e,i)=>{const a=points.get(e.from)!,b=points.get(e.to)!;return <g key={i}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="var(--border)"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2} textAnchor="middle" fontSize="11" fill="var(--blue)" role="button" tabIndex={0} onClick={()=>onFact(e.factId)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')onFact(e.factId);}}>{e.predicate.replaceAll('_',' ')}</text></g>;})}{nodes.map(n=>{const p=points.get(n.id)!;return <g key={n.id}><rect x={p.x-65} y={p.y-18} width="130" height="36" fill="var(--knowledge-surface, white)" stroke="var(--border)"/><text x={p.x} y={p.y+4} textAnchor="middle" fontSize="12"><title>{n.label}</title>{n.label.length>19?n.label.slice(0,18)+'…':n.label}</text></g>;})}</svg>;
}
